### PR TITLE
Create Web-Adv-BG

### PR DESCRIPTION
**Pull request by wseltzer**
An intro for web-adv BG

### CODE REVIEW

**Comment by caribouW3** [comment]
@wseltzer the name of the file should be the id of the group, apparently 103226, see
https://www.w3.org/admin/bg/103226/show

**Comment by caribouW3** [comment]
Also note that the "facility map" from Onboarding Information (https://w3c.github.io/Guide/participant/group.html) does not work for BG/CGs, so your template should probably not include this link.

**Comment by wseltzer** [comment]
Thanks @caribouW3 , both now fixed.

**Comment by caribouW3** [comment]
The last line  {% endif %} should also be removed (there is no conditional in the template)
Sorry for not noticing earlier

**Pull request merged**
